# These are supported funding model platforms
patreon: syiana
custom: https://www.paypal.com/donate/?return=https://www.curseforge.com/projects/283939&cn=Add+special+instructions+to+the+addon+author()&business=suiaddon%40gmail.com&bn=PP-DonationsBF:btn_donateCC_LG.gif:NonHosted&cancel_return=https://github.com/Syiana/SUI/&lc=US&item_name=SUI+(from+github.com)&cmd=_donations&rm=1&no_shipping=1&currency_code=EUR
